### ISSUE TITLE
Typo in examples/listen_for_voevents.sh

### ISSUE THREAD

**Issue by AntoniaR** [timstaley/fourpiskytools#4]
There is a missing part of the $HANDLER command, which means that the VOEvents were not being processed by the $HANDLER script

Line 14 of examples/listen_for_voevents:
`HANDLER=process_voevent_from_stdin_2.py`
should instead be
`HANDLER=./process_voevent_from_stdin_2.py`

https://github.com/4pisky/fourpiskytools/blob/f7099d6a40e4b74f7402890da854ac08a413bcda/examples/listen_for_voevents.sh#L14

**Comment by timstaley** [comment]
Hey Antonia,
thanks for this! Not sure how it slipped through, I think this has come up in email conversations with someone in the past but clearly missed this one. Hope it didn't cause you too much delay.
